# Generated by Django 6.0.1 on 2026-02-01 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('BIKE', 'Bike'), ('CAR', 'Car'), ('VAN', 'Van')], max_length=10)),
                ('price', models.PositiveIntegerField(help_text='Price per day')),
                ('seats', models.PositiveIntegerField(default=2)),
                ('transmission', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric')], default='PETROL', max_length=15)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True, help_text='Is the vehicle physically available for rent?')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.vehiclemodel')),
            ],
        ),
    ]
