# Generated by Django 6.0.1 on 2026-02-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingmodelpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingModelPayment',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online Payment'), ('COD', 'Cash on Delivery')], default='ONLINE', max_length=10),
        ),
    ]
