# Generated by Django 6.0.1 on 2026-02-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_ordermodel_is_paid_ordermodel_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_order',
        ),
    ]
